### ISSUE TITLE
AttributeError: module 'wikiextractor' has no attribute 'extract'

### ISSUE THREAD

**Issue by GokulNC** [akb89/witokit#15]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/site-packages/witokit/main.py", line 134, in _preprocess
    for json_object in tqdm(wikiextractor.extract(input_xml_filepath)):
AttributeError: module 'wikiextractor' has no attribute 'extract'
```

I don't see any such function called `extract()` here: https://github.com/attardi/wikiextractor
Any clues on how it works?

**Comment by GokulNC** [comment]
Alrighttt, got it :)
I'm supposed to do `python setup.py install`, I was doing `pip install .`

 BTW, your wikiextractor fork seems a bit outdated.
Can you please pull and merge the latest changes from the actual repo?

**Comment by GokulNC** [comment]
Also, instead of asking people to `python setup.py install`, you could just ask them to `pip install --upgrade git+https://github.com/akb89/wikiextractor` before `pip install witokit`. (Ofcourse you'll have to remove that wikiextractor dep from setup.py)

**Comment by akb89** [comment]
Hi, Thanks for using WiToKit! I don't have much time at the moment to work on this so I am trying to figure out whether it would be really worth investing time on merging the latest Wikiextractor branch. I think I would only do it if there was a known bug in my current fork or if some super useful / necessary features (for WiToKit) were added since. Otherwise I do welcome pull requests!
